// Generated by CoffeeScript 1.10.0
(function() {
  var SchedulerInput;

  SchedulerInput = (function() {
    function SchedulerInput() {
      this.addTimeListener();
      this.addSectionListener();
      this.addCourseListener();
    }

    SchedulerInput.prototype.addTimeListener = function() {
      this.add('.schd-add-time');
      return this.remove('.schd-rmv-time');
    };

    SchedulerInput.prototype.addSectionListener = function() {
      this.add('.schd-add-section');
      return this.remove('.schd-rmv-section');
    };

    SchedulerInput.prototype.addCourseListener = function() {
      this.add('.schd-add-course');
      return this.remove('.schd-rmv-course');
    };

    SchedulerInput.prototype.add = function(selector) {
      return $(selector).on('click', (function(_this) {
        return function(event) {
          var target;
          target = $(event.currentTarget);
          return target.siblings('div').last().clone(true).insertBefore(target);
        };
      })(this));
    };

    SchedulerInput.prototype.remove = function(selector) {
      return $(selector).on('click', (function(_this) {
        return function(event) {
          var siblings;
          siblings = $(event.currentTarget).siblings('div');
          console.log(siblings);
          if (siblings.length > 1) {
            return siblings.last().remove();
          }
        };
      })(this));
    };

    return SchedulerInput;

  })();

  window.SchedulerInput = SchedulerInput;

}).call(this);

//# sourceMappingURL=schedulerInput.js.map
